### ISSUE TITLE
Monitor

### ISSUE THREAD

**Issue by Dudz51** [adrianglz64/snappyrom#11]
are you able to change anything in the actual machine code monitor itself on the SS? I've always wished the register (SR) was shown broken down by bit value to easily tell which flags are set. Thank you for your tremendous support with this rom!!
![Screenshot 2024-03-05 164342](https://github.com/adrianglz64/snappyrom/assets/142706099/e41417c1-b644-4a6e-bb3e-8a265b5cec61)

**Comment by adrianglz64** [comment]
Yes, monitor improvements are planned, but I'm not quite done with the ROM disassembly yet.  All the current ROM changes are binary patches over the original ROM, which works ok for smaller stuff, but it's quickly getting out of hand.  I want to have the ROM building from source before I tackle bigger improvements like adding features to the monitor.  Unfortunately I don't have an estimate as to how long it will take yet.

**Comment by Dudz51** [comment]
You're amazing! I can't thank you for all your hard work on this!
