### ISSUE TITLE
TMP Freezes with Ultimate II+ 3.10

### ISSUE THREAD

**Issue by felipebalbi** [adrianglz64/snappyrom#12]
Hi,

pressing F5 causes C64 PAL breadbin to freeze instead of opening TMP. Is there any information you would like me to capture?

**Comment by felipebalbi** [comment]
FYI, upgraded UII+ to 3.11 and it worked fine, however TMP still says 512k REU even though I have a 16M image. I suppose that's expected.

**Comment by adrianglz64** [comment]
Glad to hear it worked fine with 3.11.  TMP was never updated to detect more than 512KB, but it should work fine even if you give it 16MB.
