### ISSUE TITLE
REU version of TMP not launched on UII+L with 16MB

### ISSUE THREAD

**Issue by vandabbin** [adrianglz64/snappyrom#5]
Hi! I'm testing out the rom on a UII+L and noticed that when launching TMP with every REU size available, it only doesn't launch the REU version when the 16MB REU is selected.

Not really a big issue but wanted to document it here

**Comment by adrianglz64** [comment]
Hi there!  This is actually a bug of sorts in SSv5's REU detection routine.  It basically checks for the presence of an REU and then counts the number of 64K banks it has.  Unfortunately, the number of banks is stored as an 8-bit value: 128K is 2 banks, 256K is 4, 512K is 8, all the way to 16MB being 256 banks, so the count wraps around to 0, which is taken to mean no REU is present.  16MB REUs really weren't a thing back in 1990 or so.

The result of this detection routine is used in stuff like the file copier and disk copier which have the option to use extra RAM as a buffer to minimize disk swapping.  I also used it to detect whether to start the REU or non-REU version of TMP.  I tried thinking of a way to let the user select which version of TMP to start, but I couldn't come up with anything that didn't make things more confusing.  Suggestions welcome!

**Comment by vandabbin** [comment]
Ahh I see! That explains it!

**Comment by trgswe** [comment]
Same on the U64, but couldn't a 16MB REU actually for instance be a special case of 255? Hope this makes sense for you, i quickly wrote this when i lokked for the above 'bug'

**Comment by adrianglz64** [comment]
It's the detection routine from the original SSv5 ROM.  As I mentioned, it counts the number of 64K banks it finds, so, yes, 128K = 2 banks, 512K = 8 banks, etc.
Unfortunately, the other original features in the ROM expect a bank count, so if I change it like you suggest then I would have to change everything else that uses the result of this detection routine.
Stuff like the file copier would think it has 64k less than it actually does, for example.  It's no big deal if you have a 16MB REU, but it would really suck if you have a 128K or 256K one.
The easiest solution would be to keep it as it is, but cap it at $FF banks.  I'll probably do that for the next release.

**Comment by trgswe** [comment]
Does 5.22 actually care how many banks/size, just did some tests and it seems to recognise 16 Mb REU (or at least it knows it at least has 512K REU) don't know what you intend to implement, i know robin of 8-bit show and tell was interested in upgrading the sprite editor. Somethibg i would like to see changed is that it actually shows banks#/size etc.

**Comment by adrianglz64** [comment]
As far as I know the v5.22 ROM only uses REU RAM as a buffer for the file and disk copiers.  It needs to know the size of the user's REU so it knows how much extra RAM it can use, and that's where the detection routine we've been talking about comes in.

You mention that when you try it with a 16MB REU it knows it has at least 512K.  Where are you seeing this?

I suppose it wouldn't be too hard to display REU size on the startup screen.  Is that what you meant?

**Comment by vandabbin** [comment]
> Same on the U64, but you should never get 256 (have you done the oh so common that you count with 1-based instead of 0- based) quickly wrote this
> 11111111 = 16 Mb = 255  banks but 256 values counting from 0
> 01111111 = 8Mb
> 00111111 = 4Mb
> 00011111= 2Mb
> 00001111 = 1Mb
> 00000111 = 512Kb
> 00000011 = 256Kb
> 00000001 = 128Kb
> 00000000 = 64 Kb = 0 Kb REU space

The problem I see here is that Adrian says it counts the banks up as an 8-bit value like so

00000000 = 0 Banks
00000001 = 1 Bank of 64k
00000010 = 2 Banks of 64k (128k)
11111111 = 255 Banks of 64k or (16,320k) which is 64k less then 16MB

Unless I'm wrong

**Comment by adrianglz64** [comment]
> The problem I see here is that Adrian says it counts the banks up as an 8-bit value like so
> 
> 00000000 = 0 Banks 00000001 = 1 Bank of 64k 00000010 = 2 Banks of 64k (128k) 11111111 = 255 Banks of 64k or (16,320k) which is 64k less then 16MB
> 

Yes, that's exactly how it works.

> Anyway, my thoughts are that maybe you could add a small chunk of code that gets run when snappy attempts to launch TMP that checks $df00 for the presence of an REU and launches the REU version if so or even insert it into the ssv5 routines. The size of the REU wouldn't really matter right? Doesn't TMP go ahead and figure that out? And it maxes out at 512k too right?

Yes, it's entirely possible to add a second REU detect routine to decide which version of TMP to start, I just decided to use the value that was already available from the Snapshot ROM.  Also, yes, TMP doesn't really use more than 512K of REU RAM.

Looking at the detection code again, I think I can patch it by changing a single byte.  I'll run some tests and if it works I'll upload an updated ROM (the patch should make the count stop $ff).

**Comment by vandabbin** [comment]
Ahh yeah that's definitely the most elegant solution! I don't see anyone saturating almost 16mb of memory using the built-in file copier

**Comment by adrianglz64** [comment]
It ended up being a 2-byte patch, but it seems to work.  The blocks free counter is messed up in the file copier, but it seems to use the REU fine.  The disk copier also seems to work fine too, but I didn't test a whole lot.

If you're curious and want to see the result of the REU detection routine bank count, go into the ML monitor and type:
```
*X0
M 9E38
```
the byte at location $9E38 is the bank count.  A 16MB REU returns FF now instead of 00.
If you're even more curious, the detection routine itself is at $F71B in the NTSC ROM, and $F71E in the PAL ROM (make sure you issue the *X0 command, otherwise you'll be looking at the kernal ROM).

[snappyrom-5.32-beta.zip](https://github.com/adrianglz64/snappyrom/files/12079602/snappyrom-5.32-beta.zip)

**Comment by vandabbin** [comment]
Cool! I'm gonna play around with it some! I am indeed interested in checking out the detection routine so thanks for pointing out it's start address!

**Comment by trgswe** [comment]
Just a quick question, is there a similar problem with the monitor (since they might have a 2Mb REU limit as a sort of " max allowed " size )  If I am not wrong, you should have similar comman to edit memory there with '*b <bank#>'

**Comment by adrianglz64** [comment]
The monitor actually handles it just fine, but it expects hex.  Basically, *R lets you set the REU bank byte stored to $DF06.  As far as I can tell it works fine all the way up to 16MB

``*R0`` for bank 0
``*RA`` for bank 10
``*R10`` for bank 16
... all the way to
``*RFF`` for bank 255

**Comment by adrianglz64** [comment]
Fixed in v5.34
