### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by Dudz51** [adrianglz64/snappyrom#9]
Is it possible to include the preferences file to allow customization? 
Instinct tells me no, this is a ROM, so I need to break out a hex editor

![image](https://github.com/adrianglz64/snappyrom/assets/142706099/d91f5154-d074-4e99-ab06-9d836b8441bd)

**Comment by adrianglz64** [comment]
It's possible to include it, but like you said, you wouldn't be able to save the modified TMP to ROM.  I will need to write some kind of ROM customizing tool at some point, but for now I want to focus on continuing with the disassembly of the original ROM.

In the meantime, I'm just about ready to release an update, so go ahead and upload a TMP (and/or) a TMP+REU customized to your liking here and I'll build you a ROM with that.

**Comment by Dudz51** [comment]
Here's my TMP+REU
[tmp.zip](https://github.com/adrianglz64/snappyrom/files/12731805/tmp.zip)

**Comment by adrianglz64** [comment]
Here's the latest ROM with your TMP+REU.
Just out of curiosity, what's your Snapshot+REU setup?  1541U/Ultimate64-based, I'm assuming?

[snappyrom-5.34-Dudz51.zip](https://github.com/adrianglz64/snappyrom/files/12747779/snappyrom-5.34-Dudz51.zip)

**Comment by Dudz51** [comment]
I wish I had real hardware! No, emulator for me. Unfortunately, I'm disabled and sitting at a desk isn't viable. Growing up I always wanted to learn ml, but with no guidance (or Internet, lol) it was an impossible task

**Comment by Dudz51** [comment]
Thank you!

**Comment by Dudz51** [comment]
Side thought, maybe part of the autoboot portion? If user has config file inserted, it will reflect changes? just a thought

**Comment by Dudz51** [comment]
Sorry, just started testing, text alignment correct, colors wrong and line separator incorrect (back-arrow 2)

**Comment by Dudz51** [comment]
You know what? I sent a .prg file by mistake, not a .d64. My fault, I'm a drag-n-drop victim. "A victim of circumstance"
[Mine.zip](https://github.com/adrianglz64/snappyrom/files/12811924/Mine.zip)

**Comment by Dudz51** [comment]
FYI - even though you've replaced the file, you MUST remove it from options and re-add and set as new default (if it's your default)- my mistake

**Comment by adrianglz64** [comment]
Absolutely nothing wrong with using an emulator.  Real hardware is great, but it also has its quirks now and then.  Both have their pros and cons.
Ok, so I'm confused.  I'm not sure what you mean by removing it from options and re-adding it.

**Comment by Dudz51** [comment]
I had reopened this issue, stating nothing had changed with the .crt you provided, I had replaced the image in vice, and nothing happened. I checked options and it was pointing to the correct file. Even restarted the emulator, same issue. Until I detached it and reattached, did it start behaving correctly. Maybe just a glitch in my system. Odd

**Comment by adrianglz64** [comment]
Did you have REU emulation disabled by any chance?  If it doesn't detect an REU it'll load the normal TMP with the standard preferences.
Anyway, glad to hear it worked!

**Comment by Dudz51** [comment]
"real hardware has quirks knowing then"

Blasphemy

**Comment by Dudz51** [comment]
Not really an issue, but you are the only one I know actually researching through this magnificent monster of a cartridge. Your work is so greatly appreciated adding TMP to it! The cartridge itself is, imho, the fastest cartridge loader out there. But like all cartridges, need a vector. Is there any way to make it work properly with Dolphin Dos? Or just enable wedge only option on power up?  Not a big deal, just not used to the commands or monitor from DD.

Do you also know anything about the undocumented feature in the Snapshot? Power up, press f3, then 1, then f8. There's an option to change interleave. I'm assuming it's just for the file copier portion only, however, in testing I can't seem to see any difference, unlike jiffydos where there clearly is a difference writing with it adjusted (through jiffydos copy itself)

**Comment by adrianglz64** [comment]
The interleave setting should affect only files written with the file copier, yes.  I've never actually tried messing with it, but I would assume it would skip that many sectors when writing files.  I'll go ahead and test it just to see if it actually does it.

As for Dolphin DOS, I'm not sure I understand.  You want to be able to load files using a parallel cable, but don't care for the rest of it?  It looks like it uses a custom kernal on the C64 side and needs a board with both RAM and ROM on the 1541.  Probably not the easiest peripheral to find these days.

**Comment by Dudz51** [comment]
Like I said, dolphin dos isn't really a big deal to me. I was just amazed at the speed. It's monitor actually shows the flags of the status register, broken into what bits are set. Very nice feature, unfortunately that's all it is, just a monitor.

Anyway, I did play around with the file copier and I can't say I see a real difference when setting the interleave. Not like when you use jiffy dos, jiffy definitely has decreased load times when you copy a file.
